// let and const hoisting
// SYNTAX ERROR,REFRENCE ERROR,TYPE ERROR diffrence

/* LET AND CONST ARE HOISTED BUT THEY EXIST IN TEMPORAL DEADZONE
   IF WE WILL TRY TO ACCES LET AND CONST BEFORE DECLARATION IT WILL THROUGH REFRENCE ERROR;
   
   A PHASE FROM HOSTING TO THE MOMENT IT WAS INITIALISED IS CALLED TEMPORAL DEADZONE;
   
   
  
*/


console.log(a);  // will give it refrence error; 
console.log(b);
let a=10;
var b = 20;
